# Use the official Python image as the base image
FROM python:3.11-slim-bookworm

# Set the working directory
WORKDIR /app

COPY . .

# Create a virtual environment and activate it, then install dependencies from the requirements.txt file
RUN python -m venv /opt/venv && \
    /opt/venv/bin/pip install --no-cache-dir --upgrade pip && \
    /opt/venv/bin/pip install --no-cache-dir -r requirements.txt

# Set the environment variable FLASK_APP
ENV FLASK_APP=run.py

# Expose port 5000
EXPOSE 5000

# Run the Flask application using the run.py file
CMD ["/opt/venv/bin/python", "run.py"]